### ISSUE TITLE
没有到期之前能不能激活

### ISSUE THREAD

**Issue by wf4867612** [pretend-m/navicat_for_mac_reset#11]
试用期到期之前激活了没生效，是不是只能到期之后激活？

**Comment by pretend-m** [comment]
不是的，任何时间都可以使用。但是,最好在14天之后使用，这样才能看出变化。然后，没生效的话，可以尝试先重启电脑，然后执行脚本，然后在打开navicat.具体的可以参考文档

**Comment by wf4867612** [comment]
可以可以👍
