### ISSUE TITLE
Mac 下16.3.3版本无效

### ISSUE THREAD

**Issue by Rover-Wong** [pretend-m/navicat_for_mac_reset#3]
之前每次到期后重新执行下脚本，都是可以再次试用的，2024-03-18到期后，再次执行脚本后无效，去对应的文件~/Library/Preferences/com.navicat.NavicatPremium.plis看了下也没有删除相关key
突然就不可使用了。

**Comment by pretend-m** [comment]
尝试重新执行脚本，然后重启电脑，再次打开navicat查看
