### ISSUE TITLE
运行脚本后，会丢失已经登录的navicat cloud账号

### ISSUE THREAD

**Issue by liuhao16** [pretend-m/navicat_for_mac_reset#7]
<img width="1100" alt="image" src="https://github.com/pretend-m/navicat_for_mac_reset/assets/39983417/083b606a-258a-4f73-9e57-106c118e1549">

**Comment by pretend-m** [comment]
hi,请提供你的版本。我在最新的17.0.8版中并未复现这个问题。可以尝试升级到最新版本。

**Comment by liuhao16** [comment]
谢谢。我升级下版本试试，我现在的版本是17.0.7

**Comment by liuhao16** [comment]
17.0.8没问题  三克油
